name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'metadata/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'metadata/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup jdk-17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Release
        run: ./gradlew assembleRelease

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Prepare APK for release
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} Kizzy-v${{ github.run_number }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1 # Prefer softprops/action-gh-release for simplicity with files
        with:
          files: Kizzy-v${{ github.run_number }}.apk
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
