name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'metadata/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'metadata/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup jdk-17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble Release
        run: ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: app/build/outputs/apk/release/**.apk

      - name: Prepare APK for release
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "No APK found in app/build/outputs/apk/release/"
            exit 1
          fi
          mv "$APK_PATH" Kizzy-v${{ github.run_number }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1 # Prefer softprops/action-gh-release for simplicity with files
        with:
          files: Kizzy-v${{ github.run_number }}.apk
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
